[package]
name = "fft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
num = "0.4"
actix-web = "4.0"
actix-files = "0.6.5"
itertools = "0.10.0"
